### ISSUE TITLE
Add support for Files.

### ISSUE THREAD

**Issue by julianpritzi** [RolandBernard/CWakan#4]
I'm trying to use this language to compare two csv tables and create a 3rd one but ther is no way to open and read/write into a file.

I'd like to have a file object. To read from and write to.

It's possible to redirect the stdin and stdout to a file.

Please Help! I need this **asap**.

**Comment by rolandbernard** [comment]
We will look into the possibility of adding the requested feature, but we can't promise anything.

**Comment by rolandbernard** [comment]
I now added the following operations:
* fopen
* fclose
* fwrite
* fread

An example is present at `examples/file_io.wk`.
